- README.md
Instructions to guide new developers over starting the front and backend.
> Added get started instructions

- WebApiBackend/WebApiBackend/Model/Flat.cs
- WebApiBackend/WebApiBackend/Model/Payment.cs
- WebApiBackend/WebApiBackend/Model/Schedule.cs
- WebApiBackend/WebApiBackend/Model/User.cs
Adding initial data model classes obtained from data model diagram
> Introducing data model classes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation-update.md
- .github/ISSUE_TEMPLATE/feature_request.md
Added issue templates for bugs, adding features and documentation to resolve issue #9
> Update issue templates

- .github/pull_request_template.md
**Relates to Github Issue:** #21
documentation
Added pull request template so all future pull requests are standardized
N/A
> Created pull request template for project

- WebApiBackend/WebApiBackend/Model/Schedule.cs
**Relates to Github Issue:** #25 
**What is the PR Type:** Bugfix
Removed MyProperty field from Schedule class
Test cases not applicable at this stage
> Removed MyProperty field from Schedule class

- C#-guidelines.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- reactjs-guidelines.md
The following files are created to resolve issue #8
Create CONTRIBUTING.md
Create reactjs-guidelines.md
Create C#-guidelines.md
Create CODE_OF_CONDUCT.md
> Create contribution guidelines and code of conduct

- .github/workflows/dotnetcore.yml
**Relates to Github Issue:** #30 
- action
Created GitHub actions to automate backend unit testing on pushes and pull requests
> Feature/#30 Create GitHub actions to automate testing

- .github/ISSUE_TEMPLATE/refactor_request.md
**Relates to Github Issue:** #62
feature
Added refactor issue template so all future refactor issues are standardized
> Feature/#62 Created refactor issue template

- WebApiBackend/WebApiBackend/Model/Payment.cs
**Relates to Github Issue:** #61 
-feature
Added description field to the Payment Model
> Feature/#61 Added description field to Payment Model

- Frontend/frontend/package.json
- Frontend/frontend/src/App.css
- Frontend/frontend/src/App.js
- Frontend/frontend/src/Components/ChoreListComponent.js
- Frontend/frontend/src/Components/Dashboard.js
**Relates to Github Issue:** #41 
Feature
This branch adds a component used for displaying a dummy list of chores with check boxes next to each chore name. Currently, this is the only component present in the dashboard component. All styling of the component is consistent with the high fidelity prototype design. 
Components have been generated using react's bootstrap module. Also, the font of the header of this component is very similar to the current background colour, making it difficult to see. This will be remedied when the dashboard is fully integrated.
> Feature/#41 Add Chores List Component for Dashboard

- WebApiBackend/WebApiBackend/Properties/launchSettings.json
- WebApiBackend/WebApiBackend/Startup.cs
**Relates to Github Issue:** #88 
feature
When the back-end is launched, a new window opens with Swagger.
> Configured back-end to launch Swagger when run

- WebApiBackend/WebApiBackend/Helpers/DevelopmentDatabaseSetup.cs
**Relates to Github Issue:** #69 
feature
Updated the test data according to the models.
- Added bank account to users
- Added description to payments
- Added UserPayments to users
> Updated test data for Payment and User

- WebApiBackend/WebApiBackend/Model/FlatManagementContext.cs
- WebApiBackend/WebApiBackend/Model/User.cs
#104 
Feature
Added a flat reference to the user model
> Feature/#104 Added flat reference to user

- Frontend/frontend/src/App.js
- Frontend/frontend/src/Views/Login.css
- Frontend/frontend/src/Views/Login.js
- Frontend/frontend/src/Views/Logout.js
- Frontend/frontend/src/Views/SplashScreen.js
**Relates to Github Issue:** #58 
**What is the PR Type:** feature
**Describe the added/fixed behaviour:** The splash screen is now displayed when the app launches and the home screen can be accessed by clicking when on the splash screen. If the screen is not clicked after a short delay, it is automatically redirected to the home page.
> Linked up splash screen to the home screen when clicked

- WebApiBackend/WebApiBackend/Controllers/UserController.cs
- WebApiBackend/WebApiBackend/Model/FlatManagementContext.cs
- WebApiBackend/WebApiBackend/Model/User.cs
#104 
Feature
Added a FlatId field to user model as Flat was still null when querying users for flats.
> Update user model

- Frontend/frontend/src/App.js
- Frontend/frontend/src/Components/Navigation.css
- Frontend/frontend/src/Components/Navigation.js
- Frontend/frontend/src/index.css
**Relates to Github Issue:** #105 
**What is the PR Type:** feature
Main pages now comply with layout as per HiFi.
> Make navbar, main app layout, comply with HiFis

- WebApiBackend/WebApiBackendTests/Helper/DatabaseSetUpHelper.cs
- WebApiBackend/WebApiBackendTests/PaymentControllerTest.cs
- WebApiBackend/WebApiBackendTests/UserControllerTest.cs
**Relates to Github Issue:** #47 
feature
- Base test class for Payment controller
- Refactored test database set-up out of UserControllerTest
The PaymentsController needs an IMapper which needs addition set-up, so test cases can't be written yet; will create a new issue for this.
Just want the refactor to be updated first.
> Base Payment unit tests

- WebApiBackend/WebApiBackend/Controllers/UserController.cs
**Relates to Github Issue:** #116
- refactoring
As Id was created in User model and used as identity, the JWT token generation was replaced with UserID. This is so there is consistency between model identity columns and claims.
> Refactor/#116 Replaces Username in JWT token generation with UserID

- WebApiBackend/WebApiBackend/Controllers/PaymentsController.cs
- WebApiBackend/WebApiBackend/WebApiBackend.csproj
#135 
Refactoring
- Updated documentation  by adding the return codes and what parameters are for 
- Changed routes for endpoints 
> Refactored PaymentController

- WebApiBackend/WebApiBackend/Controllers/PaymentsController.cs
#138 
Feature
- Added a method to get all users from a payment 
> Feature/#138 Adding method to get all users for a payment

- WebApiBackend/WebApiBackend/Model/Flat.cs
- WebApiBackend/WebApiBackend/Model/Schedule.cs
- WebApiBackend/WebApiBackend/Model/User.cs
**Relates to Github Issue:** #141 
- Refactoring
Data model classes now implement IEntity
> refactor/#141-added datamodel classes to implement IEntity

- WebApiBackend/WebApiBackend/Helpers/DevelopmentDatabaseSetup.cs
- WebApiBackend/WebApiBackendTests/FlatControllerTest.cs
- WebApiBackend/WebApiBackendTests/Helper/MapperHelper.cs
- WebApiBackend/WebApiBackendTests/PaymentControllerTest.cs
- WebApiBackend/WebApiBackendTests/WebApiBackendTests.csproj
**Relates to Github Issue:** #47
feature
- fixed mapper
- implemented test cases
- integrated with auth
> payment unit tests

- WebApiBackend/WebApiBackend/Controllers/PaymentsController.cs
- WebApiBackend/WebApiBackendTests/PaymentControllerTest.cs
**Relates to Github Issue:** 
#160 
-refactoring
Refactored PaymentController to remove any flatid query parameters
Changed PaymentControllerTests to reflect this
> Refactor PaymentsController to remove uneccessary query params

- Frontend/frontend/src/Components/Payments.js
- Frontend/frontend/src/Components/ViewPayment.js
#170 
Feature 
- Payment information now displays when a payment is clicked 
> Connect Payment and ViewPayment components 

- Frontend/frontend/src/Components/Payments.js
**Relates to Github Issue:** #171
Bug Fix
Fixed bug where new users checking payments page will give an error.
- This undefined error is caused by the API returning 404 not found thus render resultant body data as undefined.
- Now when a 404 status happens, data is by default an empty list.
- The same applies to obtaining User Contributions API.
> BUG FIX: Payments Page crashes for new users.

- WebApiBackend/WebApiBackendTests/FlatControllerTest.cs
- WebApiBackend/WebApiBackendTests/Helper/HttpContextHelper.cs
- WebApiBackend/WebApiBackendTests/PaymentControllerTest.cs
- WebApiBackend/WebApiBackendTests/UserControllerTest.cs
**Relates to Github Issue:** #175 
refactoring
- Rearranged tests into AAA pattern (Arrange, Act, Assert) for consistency across classes
- Removed redundant code
- Added comments for tests
> Refactored test classes

- Frontend/frontend/src/Components/MemberTile.js
- WebApiBackend/WebApiBackend/Controllers/FlatController.cs
- WebApiBackend/WebApiBackendTests/FlatControllerTest.cs
Closes #183
Duplicate of PR #186, fixing merge conflicts and also rearrange the new unit tests added to match AAA style.
* Feature
Tests have been added to FlatControllerTests to ensure flat creation and retrieving flat members works as intendecd
Although This pull request comes from @NathanMills1 and @williamlixu, this work was undertaken by @vaibhavnz
> Added tests for flat creation and member retrieval

- Frontend/frontend/package-lock.json
- Frontend/frontend/src/Components/Dashboard.css
- Frontend/frontend/src/Components/Dashboard.js
- Frontend/frontend/src/Components/DashboardPayments.js
- Frontend/frontend/src/Components/PaymentModule.js
- Frontend/frontend/src/Components/Payments.css
- Frontend/frontend/src/Components/Payments.js
**Relates to Github Issue:** #96
**What is the PR Type:** feature
**Describe the added/fixed behaviour:** Added payment component as shown in [HiFi](https://github.com/SE701ProjectGroup4/Flatmate-Management-System/wiki/High-Fidelity-Design#general)
Looks like changes from #179 might have to be applied here, wasn't sure how to reduce code duplication further.
> Add payments to dashboard

- Frontend/frontend/src/Components/DashboardPayments.js
Closes #199
* Bug fix
* Fixed bug where new users checking dashboard will give an error.
* This undefined error is caused by the API returning 404 not found thus render resultant body data as undefined.
* Fixed in the same way as in #179
> Fix dashboard having no payments

- Frontend/frontend/src/Components/ChoresUpdateButton.js
- Frontend/frontend/src/Util/APIRequest.js
- Frontend/frontend/src/Views/Login.js
Closes #209
Bug fix
Fixes spelling of the word member
> Fixed spelling of member on login page

- WebApiBackend/WebApiBackend/Controllers/UserController.cs
- WebApiBackend/WebApiBackendTests/UserControllerTest.cs
Closes #216 
- feature
The ID of the currently logged in user can be retrieved by calling GET /api/User/getUserID
n/a
> Added GET user ID call

- Frontend/frontend/.eslintignore
- Frontend/frontend/.eslintrc
- Frontend/frontend/package-lock.json
- Frontend/frontend/package.json
Closes #211 
**What is the PR Type:** feature
Linter runs on frontend code. Pre-commit hook set up to run linter on committed files.
> Configured linter for frontend code

- WebApiBackend/WebApiBackend/Dto/ChoresDTO.cs
- WebApiBackend/WebApiBackend/Dto/UserDTO.cs
- WebApiBackend/WebApiBackend/Model/Chores.cs
- WebApiBackend/WebApiBackendTests/ChoreMapperTest.cs
- WebApiBackend/WebApiBackendTests/Helper/MapperHelper.cs
Closes #212 and #223 
**What is the PR Type: Feature** 
Updated model and DTO for chores to match description from meeting in wiki.
Updated user DTO so that id is returned on getMembers
Matches the DTO we discussed in the meeting and [described here](https://github.com/SOFTENG701G1/Flatmate-Management-System/wiki/Chores-API)
When creating a chore, the current DTO would take a user ID to assign the chore. However, I don't believe the front-end has any notion of the user ids of the flatmates. This is because getMembers returns a 0-value for all user ids. I have updated the Users DTO accordingly.
> Updated chores model class and DTO

- Frontend/frontend/src/Util/APIRequest.js
- WebApiBackend/WebApiBackend/Controllers/UserController.cs
- WebApiBackend/WebApiBackend/Dto/UserIdDTO.cs
- WebApiBackend/WebApiBackendTests/UserControllerTest.cs
Closes #228
Feature
Added a POST request for retrieving user IDs based on provided usernames. Returns a JSON object with usernames as a key and the id as a value. If the username was not found, its value is assigned to '0'.
n/a
> An API call for getting userIds based on their usernames

- WebApiBackend/WebApiBackend/Controllers/ChoreController.cs
Also removed a console.writeLine() and change comments that mention payments to mention chores
Bug fix Closes #251
Now correctly returns assignees ids
> Fixes bug  #251 where assignee's ids are all zero. 

- Frontend/frontend/src/Components/Chores.js
- Frontend/frontend/src/Components/ChoresDialog.js
- Frontend/frontend/src/Util/APIRequest.js
Closes #247 
-feature
Added API call to the create chores dialog so new Chores generated by the chores dialog are sent to the API and added to the database. Prettier changes applied to the API requests file to update some formatting and syntax, this is why the whole file looks like it is changed.
Mob programmed with: @pabloSushibar @vee-christella @misl000
> Feature/#247 Create new chores

- WebApiBackend/WebApiBackend/Controllers/BaseController.cs
Closes #256
- Bug
Remove unneeded API that was causing duplicate definitions of the delete endpoint at `"{id}"`.
> Remove unneeded delete API to fix Swagger build

- Frontend/frontend/src/Util/Utils.js
Closes #258 
- Refactor
* Rename date -> dateToFormat to stop redefining
* Use template literal instead of string concat
> Rename date -> dateToFormat to stop redefining

- Frontend/frontend/src/App.js
- Frontend/frontend/src/Components/Navigation.js
- Frontend/frontend/src/Components/UserProfile.js
- Frontend/frontend/src/Components/UserProfileDetails.css
- Frontend/frontend/src/Components/UserProfileDetails.js
- Frontend/frontend/src/Util/APIRequest.js
Closes #233 
Unblocks #235 
Feature
-->
- Added API Calls for getUserInfo and EditUserInfo
- Added UserProfile and User Profile Details Components
- Added link to user profile from the main navbar
TODO- Add editing
> Added User Profile Page

- WebApiBackend/WebApiBackend/Controllers/ChoreController.cs
- WebApiBackend/WebApiBackendTests/ChoreControllerTest.cs
… backend
Added functionality to flag a chore as completed on the backend and added associated endpoint. And added tests
Closes #239
> Added functionality to flag a chore as completed on the backend and added associated endpoint

- Frontend/frontend/src/Components/Chores.js
- Frontend/frontend/src/Util/APIRequest.js
- WebApiBackend/WebApiBackend/Controllers/BaseController.cs
- WebApiBackend/WebApiBackend/Controllers/ChoreController.cs
Closes #248  
- Feature
New API call added to APIRequest that calls the delete chore endpoint.
Added button to chore component to allow users to delete chore. Calls new API call on click.
Fixed path param in backend to match the name in method param.
Mob programmed with @vee-christella @misl000 @icam308
> Added API call to delete chores and button on chores page to call this.

- Frontend/frontend/src/Components/Chores.js
- Frontend/frontend/src/Util/APIRequest.js
Closes #123  
- Feature
Added API call to chore endpoint that marks chores complete when provided the chores Id. Added on click method to the chore cell that calls this endpoint with the chore id as a parameter. Prettier formatting applied to some of the new functions in the APIRequest file.
Pair programmed with @pabloSushibar
> Mark chores complete from frontend #123

- Frontend/frontend/src/Components/CheckBoxListComponent.js
- Frontend/frontend/src/Components/Dashboard.js
- Frontend/frontend/src/Components/DashboardChores.js
Closes #180 
Feature
Checkbox list on dashboard now makes the appropriate api calls to get/set chores. Chores are listed by description, and users can mark chores as completed. Currently all chores for the flat are displayed regardless of assigned user.
N/A
> added basic integration of chores with dashboard

- Frontend/frontend/src/Components/AddMember.js
Closes #271  
Feature
Once an addMember request is submitted the page will refresh to show the newly added member
> Fixed Refresh after User add

- Frontend/frontend/src/Components/Payments.css
- Frontend/frontend/src/Components/Payments.js
Closes # 276
Please select type that applies from below:
- feature
This PR enable toggling between modes like light and dark.
> Toggle feature added for headers

- Frontend/frontend/src/Components/NewPayment.css
- Frontend/frontend/src/Components/NewPayment.js
Closes #278
Feature
The date and frequency can now be selected using Material UI elements. They are now passed to the backend correctly.
> Add date picker and frequency picker

- Frontend/frontend/src/Components/Chores.js
- Frontend/frontend/src/Components/ChoresDialog.js
- Frontend/frontend/src/Components/chores.css
Closes #282  
-Feature
Style changes to match the chores page with the rest of the application. Removed some unneeded console logs as well.
- No testing or docs as only style changes
> Changes styling to be consistent with rest of app

- README.md
Closes #285 
Documentation
Added a line to the README which indicates the relationship of this project to the SOFTENG 701 course.
N/A
> updated readme to include SOFTENG 701 reference

- docs/js-guidelines.md
Associated with #220 but wiki needs additional change before #220 can be closed.
documentation
JS guidelines updated to reflect project's use of AirBnB's JS style guidelines.
The sidebar for the wiki needs to be updated separately before #220 can be closed.
Code existing before the introduction of the project's new style guidelines do not comply with the new standards, but all new code should conform to the style guidelines. Any changes made to existing code should also be refactored if possible to match the new style guidelines.
> updated frontend js style guidelines

- WebApiBackend/WebApiBackend/Dto/ChoreDTO.cs
- WebApiBackend/WebApiBackend/Model/Chore.cs
- WebApiBackend/WebApiBackendTests/ChoreControllerTest.cs
Closes #213
testing
- Created test for BadRequest on chore with nonexistent assignee
- Improved CreateChore test by making it assert that the new chore is in the repo
- Modified TestGetChores to assert that the correct chores are returned\
- Added Equals methods to Chore and ChoreDTO
This PR is here to get a preliminary review. It can easily be updated with further commits as more work is done
> Implemented more unit tests for Chore controller
